### ISSUE TITLE
Unable to POST waypoint

### ISSUE THREAD

**Issue by Pranava29** [ugcs/ugcs-java-sdk#3]
Im getting the below error on trying to post a waypoint by 

java -cp .:* com.ugcs.ucs.client.samples.UploadSingleWaypointRoute UploadSingl
eWaypointRoute -w "56.9761591,24.0730345,100.0" -s 5.0 "EMU-COPTER-17"

`java.lang.Exception: Sessions number exceeded the maximum allowed for <hyper text='version <b>Open</b>' data='buy=sessionsLimit' action=event />.
	at com.ugcs.ucs.client.Client.execute(Client.java:101)
	at com.ugcs.ucs.client.Client.execute(Client.java:107)
	at com.ugcs.ucs.client.ClientSession.login(ClientSession.java:47)
	at com.ugcs.ucs.client.samples.UploadSingleWaypointRoute.uploadSingleWaypointRoute(UploadSingleWaypointRoute.java:96)
	at com.ugcs.ucs.client.samples.UploadSingleWaypointRoute.main(UploadSingleWaypointRoute.java:62)`

**Comment by episarenko** [comment]
Hi!

You are getting this message because of the active sessions cap for the free version (which is set to 1). Just close the desktop client app and try to run the sample again. It should work.
